# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # Using gomod for golang
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
